Bugfix: test psgwd binary as user not root

diff --git a/plugins/psgw/route/psgwd_exec b/plugins/psgw/route/psgwd_exec
--- a/plugins/psgw/route/psgwd_exec
+++ b/plugins/psgw/route/psgwd_exec
@@ -1,5 +1,15 @@
 #!/bin/bash
 
+[ -z "$PSGWD_BINARY" ] && {
+    echo "ERROR: missing PSGWD_BINARY"
+    exit 1
+}
+
+[ -x "$PSGWD_BINARY" ] || {
+    echo "ERROR: $PSGWD_BINARY is not executable"
+    exit 1
+}
+
 [ -n "$SLURM_SPANK_PSGW_ENV" ] && {
   set -a; eval "$SLURM_SPANK_PSGW_ENV"
   unset SLURM_SPANK_PSGW_ENV; set +a
