psport4 is the preview from ParaStaton 4 libpsport and usefull for ParaStation FE. This Version works only over Ethernet.
git-svn-id: http://svn.ipd.uka.de/repos/ParaStation/trunk/mgmt@1062 34291a86-62e8-0310-8159-f060f8a2ee4e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1242,6 +1242,8 @@ ac_config_files="$ac_config_files lib/pshal/Makefile"
 
 ac_config_files="$ac_config_files lib/psport/Makefile"
 
+ac_config_files="$ac_config_files lib/psport4/Makefile"
+
 ac_config_files="$ac_config_files lib/arg/Makefile"
 
 ac_config_files="$ac_config_files lib/pvar/Makefile"
@@ -1371,7 +1373,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1374: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1376: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1538,7 +1540,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1541: error: ambiguous option: $1
+    { { echo "$as_me:1543: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1557,7 +1559,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1560: error: unrecognized option: $1
+  -*) { { echo "$as_me:1562: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1598,6 +1600,7 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "lib/pshal/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pshal/Makefile" ;;
   "lib/psport/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/psport/Makefile" ;;
+  "lib/psport4/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/psport4/Makefile" ;;
   "lib/arg/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/arg/Makefile" ;;
   "lib/pvar/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pvar/Makefile" ;;
   "lib/pse/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pse/Makefile" ;;
@@ -1608,7 +1611,7 @@ do
   "bin/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/Makefile" ;;
   "bin/test/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/test/Makefile" ;;
   "dist/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist/Makefile" ;;
-  *) { { echo "$as_me:1611: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1614: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1824,7 +1827,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1827: creating $ac_file" >&5
+    { echo "$as_me:1830: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1842,7 +1845,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1845: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1848: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1855,7 +1858,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1858: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1861: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
