add dist to make a distribution
git-svn-id: http://svn.ipd.uka.de/repos/ParaStation/trunk/mgmt@919 34291a86-62e8-0310-8159-f060f8a2ee4e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1250,6 +1250,8 @@ ac_config_files="$ac_config_files bin/Makefile"
 
 ac_config_files="$ac_config_files bin/test/Makefile"
 
+ac_config_files="$ac_config_files dist/Makefile"
+
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -1359,7 +1361,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1362: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1364: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1526,7 +1528,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1529: error: ambiguous option: $1
+    { { echo "$as_me:1531: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1545,7 +1547,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1548: error: unrecognized option: $1
+  -*) { { echo "$as_me:1550: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1592,7 +1594,8 @@ do
   "kern/Makefile.include" ) CONFIG_FILES="$CONFIG_FILES kern/Makefile.include" ;;
   "bin/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/Makefile" ;;
   "bin/test/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/test/Makefile" ;;
-  *) { { echo "$as_me:1595: error: invalid argument: $ac_config_target" >&5
+  "dist/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist/Makefile" ;;
+  *) { { echo "$as_me:1598: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1806,7 +1809,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1809: creating $ac_file" >&5
+    { echo "$as_me:1812: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1824,7 +1827,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1827: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1830: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1837,7 +1840,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1840: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1843: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
