Remove 'Transparent tcp' option. Do not create obsolete lib/psport4/Makefile, lib/psport4shm/Makefile and   dist_fe/Makefile.
git-svn-id: http://svn.ipd.uka.de/repos/ParaStation/trunk/mgmt@3052 34291a86-62e8-0310-8159-f060f8a2ee4e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -613,11 +613,6 @@ if test -n "$ac_init_help"; then
    esac
   cat <<\EOF
 
-Optional Features:
-  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
-  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
-  --enable-ttcp    (Transparent tcp (default: disabled)
-
 Report bugs to <"eicker@par-tec.com">.
 EOF
 fi
@@ -801,7 +796,7 @@ if test -z "$CONFIG_SITE"; then
 fi
 for ac_site_file in $CONFIG_SITE; do
   if test -r "$ac_site_file"; then
-    { echo "$as_me:804: loading site script $ac_site_file" >&5
+    { echo "$as_me:799: loading site script $ac_site_file" >&5
 echo "$as_me: loading site script $ac_site_file" >&6;}
     cat "$ac_site_file" >&5
     . "$ac_site_file"
@@ -812,7 +807,7 @@ if test -r "$cache_file"; then
   # Some versions of bash will fail to source /dev/null (special
   # files actually), so we avoid doing that.
   if test -f "$cache_file"; then
-    { echo "$as_me:815: loading cache $cache_file" >&5
+    { echo "$as_me:810: loading cache $cache_file" >&5
 echo "$as_me: loading cache $cache_file" >&6;}
     case $cache_file in
       [\\/]* | ?:[\\/]* ) . $cache_file;;
@@ -820,7 +815,7 @@ echo "$as_me: loading cache $cache_file" >&6;}
     esac
   fi
 else
-  { echo "$as_me:823: creating cache $cache_file" >&5
+  { echo "$as_me:818: creating cache $cache_file" >&5
 echo "$as_me: creating cache $cache_file" >&6;}
   >$cache_file
 fi
@@ -836,21 +831,21 @@ for ac_var in `(set) 2>&1 |
   eval ac_new_val="\$ac_env_${ac_var}_value"
   case $ac_old_set,$ac_new_set in
     set,)
-      { echo "$as_me:839: error: \`$ac_var' was set to \`$ac_old_val' in the previous run" >&5
+      { echo "$as_me:834: error: \`$ac_var' was set to \`$ac_old_val' in the previous run" >&5
 echo "$as_me: error: \`$ac_var' was set to \`$ac_old_val' in the previous run" >&2;}
       ac_cache_corrupted=: ;;
     ,set)
-      { echo "$as_me:843: error: \`$ac_var' was not set in the previous run" >&5
+      { echo "$as_me:838: error: \`$ac_var' was not set in the previous run" >&5
 echo "$as_me: error: \`$ac_var' was not set in the previous run" >&2;}
       ac_cache_corrupted=: ;;
     ,);;
     *)
       if test "x$ac_old_val" != "x$ac_new_val"; then
-        { echo "$as_me:849: error: \`$ac_var' has changed since the previous run:" >&5
+        { echo "$as_me:844: error: \`$ac_var' has changed since the previous run:" >&5
 echo "$as_me: error: \`$ac_var' has changed since the previous run:" >&2;}
-        { echo "$as_me:851:   former value:  $ac_old_val" >&5
+        { echo "$as_me:846:   former value:  $ac_old_val" >&5
 echo "$as_me:   former value:  $ac_old_val" >&2;}
-        { echo "$as_me:853:   current value: $ac_new_val" >&5
+        { echo "$as_me:848:   current value: $ac_new_val" >&5
 echo "$as_me:   current value: $ac_new_val" >&2;}
         ac_cache_corrupted=:
       fi;;
@@ -869,9 +864,9 @@ echo "$as_me:   current value: $ac_new_val" >&2;}
   fi
 done
 if $ac_cache_corrupted; then
-  { echo "$as_me:872: error: changes in the environment can compromise the build" >&5
+  { echo "$as_me:867: error: changes in the environment can compromise the build" >&5
 echo "$as_me: error: changes in the environment can compromise the build" >&2;}
-  { { echo "$as_me:874: error: run \`make distclean' and/or \`rm $cache_file' and start over" >&5
+  { { echo "$as_me:869: error: run \`make distclean' and/or \`rm $cache_file' and start over" >&5
 echo "$as_me: error: run \`make distclean' and/or \`rm $cache_file' and start over" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -891,10 +886,10 @@ esac
 echo "#! $SHELL" >conftest.sh
 echo  "exit 0"   >>conftest.sh
 chmod +x conftest.sh
-if { (echo "$as_me:894: PATH=\".;.\"; conftest.sh") >&5
+if { (echo "$as_me:889: PATH=\".;.\"; conftest.sh") >&5
   (PATH=".;."; conftest.sh) 2>&5
   ac_status=$?
-  echo "$as_me:897: \$? = $ac_status" >&5
+  echo "$as_me:892: \$? = $ac_status" >&5
   (exit $ac_status); }; then
   ac_path_separator=';'
 else
@@ -920,7 +915,7 @@ for ac_dir in "scripts" $srcdir/"scripts"; do
   fi
 done
 if test -z "$ac_aux_dir"; then
-  { { echo "$as_me:923: error: cannot find install-sh or install.sh in \"scripts\" $srcdir/\"scripts\"" >&5
+  { { echo "$as_me:918: error: cannot find install-sh or install.sh in \"scripts\" $srcdir/\"scripts\"" >&5
 echo "$as_me: error: cannot find install-sh or install.sh in \"scripts\" $srcdir/\"scripts\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -930,11 +925,11 @@ ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 
 # Make sure we can run config.sub.
 $ac_config_sub sun4 >/dev/null 2>&1 ||
-  { { echo "$as_me:933: error: cannot run $ac_config_sub" >&5
+  { { echo "$as_me:928: error: cannot run $ac_config_sub" >&5
 echo "$as_me: error: cannot run $ac_config_sub" >&2;}
    { (exit 1); exit 1; }; }
 
-echo "$as_me:937: checking build system type" >&5
+echo "$as_me:932: checking build system type" >&5
 echo $ECHO_N "checking build system type... $ECHO_C" >&6
 if test "${ac_cv_build+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -943,16 +938,16 @@ else
 test -z "$ac_cv_build_alias" &&
   ac_cv_build_alias=`$ac_config_guess`
 test -z "$ac_cv_build_alias" &&
-  { { echo "$as_me:946: error: cannot guess build type; you must specify one" >&5
+  { { echo "$as_me:941: error: cannot guess build type; you must specify one" >&5
 echo "$as_me: error: cannot guess build type; you must specify one" >&2;}
    { (exit 1); exit 1; }; }
 ac_cv_build=`$ac_config_sub $ac_cv_build_alias` ||
-  { { echo "$as_me:950: error: $ac_config_sub $ac_cv_build_alias failed." >&5
+  { { echo "$as_me:945: error: $ac_config_sub $ac_cv_build_alias failed." >&5
 echo "$as_me: error: $ac_config_sub $ac_cv_build_alias failed." >&2;}
    { (exit 1); exit 1; }; }
 
 fi
-echo "$as_me:955: result: $ac_cv_build" >&5
+echo "$as_me:950: result: $ac_cv_build" >&5
 echo "${ECHO_T}$ac_cv_build" >&6
 build=$ac_cv_build
 build_cpu=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
@@ -962,7 +957,7 @@ build_os=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 test -z "$build_alias" &&
   build_alias=$ac_cv_build
 
-echo "$as_me:965: checking host system type" >&5
+echo "$as_me:960: checking host system type" >&5
 echo $ECHO_N "checking host system type... $ECHO_C" >&6
 if test "${ac_cv_host+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -971,12 +966,12 @@ else
 test -z "$ac_cv_host_alias" &&
   ac_cv_host_alias=$ac_cv_build_alias
 ac_cv_host=`$ac_config_sub $ac_cv_host_alias` ||
-  { { echo "$as_me:974: error: $ac_config_sub $ac_cv_host_alias failed" >&5
+  { { echo "$as_me:969: error: $ac_config_sub $ac_cv_host_alias failed" >&5
 echo "$as_me: error: $ac_config_sub $ac_cv_host_alias failed" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
-echo "$as_me:979: result: $ac_cv_host" >&5
+echo "$as_me:974: result: $ac_cv_host" >&5
 echo "${ECHO_T}$ac_cv_host" >&6
 host=$ac_cv_host
 host_cpu=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
@@ -986,7 +981,7 @@ host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 test -z "$host_alias" &&
   host_alias=$ac_cv_host
 
-echo "$as_me:989: checking target system type" >&5
+echo "$as_me:984: checking target system type" >&5
 echo $ECHO_N "checking target system type... $ECHO_C" >&6
 if test "${ac_cv_target+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -995,12 +990,12 @@ else
 test "x$ac_cv_target_alias" = "x" &&
   ac_cv_target_alias=$ac_cv_host_alias
 ac_cv_target=`$ac_config_sub $ac_cv_target_alias` ||
-  { { echo "$as_me:998: error: $ac_config_sub $ac_cv_target_alias failed" >&5
+  { { echo "$as_me:993: error: $ac_config_sub $ac_cv_target_alias failed" >&5
 echo "$as_me: error: $ac_config_sub $ac_cv_target_alias failed" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
-echo "$as_me:1003: result: $ac_cv_target" >&5
+echo "$as_me:998: result: $ac_cv_target" >&5
 echo "${ECHO_T}$ac_cv_target" >&6
 target=$ac_cv_target
 target_cpu=`echo $ac_cv_target | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
@@ -1019,7 +1014,7 @@ test -z "$target_alias" &&
 if test -n "$ac_tool_prefix"; then
   # Extract the first word of "${ac_tool_prefix}ranlib", so it can be a program name with args.
 set dummy ${ac_tool_prefix}ranlib; ac_word=$2
-echo "$as_me:1022: checking for $ac_word" >&5
+echo "$as_me:1017: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_RANLIB+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1034,7 +1029,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_RANLIB="${ac_tool_prefix}ranlib"
-echo "$as_me:1037: found $ac_dir/$ac_word" >&5
+echo "$as_me:1032: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1042,10 +1037,10 @@ fi
 fi
 RANLIB=$ac_cv_prog_RANLIB
 if test -n "$RANLIB"; then
-  echo "$as_me:1045: result: $RANLIB" >&5
+  echo "$as_me:1040: result: $RANLIB" >&5
 echo "${ECHO_T}$RANLIB" >&6
 else
-  echo "$as_me:1048: result: no" >&5
+  echo "$as_me:1043: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1054,7 +1049,7 @@ if test -z "$ac_cv_prog_RANLIB"; then
   ac_ct_RANLIB=$RANLIB
   # Extract the first word of "ranlib", so it can be a program name with args.
 set dummy ranlib; ac_word=$2
-echo "$as_me:1057: checking for $ac_word" >&5
+echo "$as_me:1052: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_ac_ct_RANLIB+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1069,7 +1064,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_ac_ct_RANLIB="ranlib"
-echo "$as_me:1072: found $ac_dir/$ac_word" >&5
+echo "$as_me:1067: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1078,10 +1073,10 @@ fi
 fi
 ac_ct_RANLIB=$ac_cv_prog_ac_ct_RANLIB
 if test -n "$ac_ct_RANLIB"; then
-  echo "$as_me:1081: result: $ac_ct_RANLIB" >&5
+  echo "$as_me:1076: result: $ac_ct_RANLIB" >&5
 echo "${ECHO_T}$ac_ct_RANLIB" >&6
 else
-  echo "$as_me:1084: result: no" >&5
+  echo "$as_me:1079: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1099,19 +1094,6 @@ path_cleanup()
 		echo `pwd`/$1 ;;
 	esac
 }
-
-# default is no
-# Check whether --enable-ttcp or --disable-ttcp was given.
-if test "${enable_ttcp+set}" = set; then
-  enableval="$enable_ttcp"
-
-	TTCP_ENABLED=$enableval
-
-else
-
-	TTCP_ENABLED="no"
-
-fi;
 
 TOP_SRCDIR=`cd \`dirname $0\`;pwd`
 
@@ -1147,10 +1129,6 @@ ac_config_files="$ac_config_files lib/Makefile.sharedlib"
 
 ac_config_files="$ac_config_files lib/Makefile.staticlib"
 
-ac_config_files="$ac_config_files lib/psport4/Makefile"
-
-ac_config_files="$ac_config_files lib/psport4shm/Makefile"
-
 ac_config_files="$ac_config_files lib/pse/Makefile"
 
 ac_config_files="$ac_config_files lib/psi/Makefile"
@@ -1166,8 +1144,6 @@ ac_config_files="$ac_config_files bin/Makefile"
 ac_config_files="$ac_config_files docu/Makefile"
 
 ac_config_files="$ac_config_files docu/Doxyfile"
-
-ac_config_files="$ac_config_files dist_fe/Makefile"
 
 ac_config_files="$ac_config_files dist_docu/Makefile"
 
@@ -1282,7 +1258,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1285: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1261: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1449,7 +1425,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1452: error: ambiguous option: $1
+    { { echo "$as_me:1428: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1468,7 +1444,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1471: error: unrecognized option: $1
+  -*) { { echo "$as_me:1447: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1507,8 +1483,6 @@ do
   "lib/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/Makefile" ;;
   "lib/Makefile.sharedlib" ) CONFIG_FILES="$CONFIG_FILES lib/Makefile.sharedlib" ;;
   "lib/Makefile.staticlib" ) CONFIG_FILES="$CONFIG_FILES lib/Makefile.staticlib" ;;
-  "lib/psport4/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/psport4/Makefile" ;;
-  "lib/psport4shm/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/psport4shm/Makefile" ;;
   "lib/pse/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pse/Makefile" ;;
   "lib/psi/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/psi/Makefile" ;;
   "lib/pscommon/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pscommon/Makefile" ;;
@@ -1517,10 +1491,9 @@ do
   "bin/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/Makefile" ;;
   "docu/Makefile" ) CONFIG_FILES="$CONFIG_FILES docu/Makefile" ;;
   "docu/Doxyfile" ) CONFIG_FILES="$CONFIG_FILES docu/Doxyfile" ;;
-  "dist_fe/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist_fe/Makefile" ;;
   "dist_docu/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist_docu/Makefile" ;;
   "dist_mgmt/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist_mgmt/Makefile" ;;
-  *) { { echo "$as_me:1523: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1496: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1614,7 +1587,6 @@ s,@target_vendor@,$target_vendor,;t t
 s,@target_os@,$target_os,;t t
 s,@RANLIB@,$RANLIB,;t t
 s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
-s,@TTCP_ENABLED@,$TTCP_ENABLED,;t t
 s,@CFLAG_WALL@,$CFLAG_WALL,;t t
 s,@CFLAG_G@,$CFLAG_G,;t t
 s,@CFLAG_COMPAT@,$CFLAG_COMPAT,;t t
@@ -1732,7 +1704,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1735: creating $ac_file" >&5
+    { echo "$as_me:1707: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1750,7 +1722,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1753: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1725: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1763,7 +1735,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1766: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1738: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -1821,5 +1793,4 @@ fi
 # Local Variables:
 #  compile-command: "autoconf"
 # End:
-#
 #
