Tru64 port and cleanups
git-svn-id: http://svn.ipd.uka.de/repos/ParaStation/trunk/mgmt@902 34291a86-62e8-0310-8159-f060f8a2ee4e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1198,9 +1198,12 @@ linux)
 	CFLAG_G=-g
 	CPPFLAG_MMD=-MMD
 	DEPEXTENSION=.d
+	TRU64FILEADD=
 	;;
 osf5.1)
 	PSM_OSDIR=kern/OSF1
+	ac_config_files="$ac_config_files kern/OSF1/Makefile"
+
 	if test "$MCPBINHEADERDIRauto" = "yes"; then
 		MCPBINHEADERDIR=`path_cleanup $srcdir`/kern/mcp/build_nozc
 	fi;
@@ -1209,6 +1212,7 @@ osf5.1)
 	CFLAG_COMPAT="-FIcompat_tru64.h"
 	CPPFLAG_MMD=-MD
 	DEPEXTENSION=.o.d
+	TRU64FILEADD=_tru64
 #	AC_CONFIG_FILES([kern/OSF1/Makefile])
 	;;
 *)
@@ -1355,7 +1359,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1358: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1362: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1522,7 +1526,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1525: error: ambiguous option: $1
+    { { echo "$as_me:1529: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1541,7 +1545,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1544: error: unrecognized option: $1
+  -*) { { echo "$as_me:1548: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1578,6 +1582,7 @@ do
   # Handling of arguments.
   "kern/Linux/Makefile" ) CONFIG_FILES="$CONFIG_FILES kern/Linux/Makefile" ;;
   "kern/Linux/Makefile.second" ) CONFIG_FILES="$CONFIG_FILES kern/Linux/Makefile.second" ;;
+  "kern/OSF1/Makefile" ) CONFIG_FILES="$CONFIG_FILES kern/OSF1/Makefile" ;;
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "lib/pshal/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pshal/Makefile" ;;
   "lib/psport/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/psport/Makefile" ;;
@@ -1587,7 +1592,7 @@ do
   "kern/Makefile.include" ) CONFIG_FILES="$CONFIG_FILES kern/Makefile.include" ;;
   "bin/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/Makefile" ;;
   "bin/test/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/test/Makefile" ;;
-  *) { { echo "$as_me:1590: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1595: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1691,6 +1696,7 @@ s,@CFLAG_G@,$CFLAG_G,;t t
 s,@CFLAG_COMPAT@,$CFLAG_COMPAT,;t t
 s,@CPPFLAG_MMD@,$CPPFLAG_MMD,;t t
 s,@DEPEXTENSION@,$DEPEXTENSION,;t t
+s,@TRU64FILEADD@,$TRU64FILEADD,;t t
 CEOF
 
 EOF
@@ -1800,7 +1806,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1803: creating $ac_file" >&5
+    { echo "$as_me:1809: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1818,7 +1824,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1821: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1827: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1831,7 +1837,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1834: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1840: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
