Tru64 adaption
git-svn-id: http://svn.ipd.uka.de/repos/ParaStation/trunk/mgmt@896 34291a86-62e8-0310-8159-f060f8a2ee4e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1123,13 +1123,49 @@ if test "${with_lanaitools+set}" = set; then
 
 else
 
-		if MYRI_HOME=`which lanai-gcc` ; then
-#			MYRI_HOME=`which lanai-gcc`
-			MYRI_HOME=`dirname $MYRI_HOME`/..
-			MYRI_HOME=`path_cleanup $MYRI_HOME`
-			echo " $MYRI_HOME"
-		else
+		# Extract the first word of "lanai-gcc", so it can be a program name with args.
+set dummy lanai-gcc; ac_word=$2
+echo "$as_me:1128: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_lanaigccpath+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $lanaigccpath in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_lanaigccpath="$lanaigccpath" # Let the user override the test with a path.
+  ;;
+  *)
+  ac_save_IFS=$IFS; IFS=$ac_path_separator
+ac_dummy="$PATH"
+for ac_dir in $ac_dummy; do
+  IFS=$ac_save_IFS
+  test -z "$ac_dir" && ac_dir=.
+  if $as_executable_p "$ac_dir/$ac_word"; then
+   ac_cv_path_lanaigccpath="$ac_dir/$ac_word"
+   echo "$as_me:1145: found $ac_dir/$ac_word" >&5
+   break
+fi
+done
+
+  ;;
+esac
+fi
+lanaigccpath=$ac_cv_path_lanaigccpath
+
+if test -n "$lanaigccpath"; then
+  echo "$as_me:1156: result: $lanaigccpath" >&5
+echo "${ECHO_T}$lanaigccpath" >&6
+else
+  echo "$as_me:1159: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+		if test -z "$lanaigccpath" ; then
 			MCPBINHEADERDIRauto=yes
+		else
+			MYRI_HOME=`dirname $lanaigccpath`/..
+			MYRI_HOME=`path_cleanup $MYRI_HOME`
+#			echo " $MYRI_HOME"
 		fi
 
 fi;
@@ -1158,11 +1194,21 @@ linux)
 	if test "$MCPBINHEADERDIRauto" = "yes"; then
 		MCPBINHEADERDIR=`path_cleanup $srcdir`/kern/mcp/build
 	fi;
+	CFLAG_WALL="-W -Wall -Wno-unused"
+	CFLAG_G=-g
+	CPPFLAG_MMD=-MMD
+	DEPEXTENSION=.d
 	;;
 osf5.1)
+	PSM_OSDIR=kern/OSF1
 	if test "$MCPBINHEADERDIRauto" = "yes"; then
 		MCPBINHEADERDIR=`path_cleanup $srcdir`/kern/mcp/build_nozc
 	fi;
+	CFLAG_WALL="-w0  -msg_disable incomparry,unreachcode"
+	CFLAG_G=-g3
+	CFLAG_COMPAT="-FIcompat_tru64.h"
+	CPPFLAG_MMD=-MD
+	DEPEXTENSION=.o.d
 #	AC_CONFIG_FILES([kern/OSF1/Makefile])
 	;;
 *)
@@ -1197,6 +1243,8 @@ ac_config_files="$ac_config_files kern/mcp/Makefile"
 ac_config_files="$ac_config_files kern/Makefile.include"
 
 ac_config_files="$ac_config_files bin/Makefile"
+
+ac_config_files="$ac_config_files bin/test/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -1307,7 +1355,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1310: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1358: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1474,7 +1522,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1477: error: ambiguous option: $1
+    { { echo "$as_me:1525: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1493,7 +1541,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1496: error: unrecognized option: $1
+  -*) { { echo "$as_me:1544: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1538,7 +1586,8 @@ do
   "kern/mcp/Makefile" ) CONFIG_FILES="$CONFIG_FILES kern/mcp/Makefile" ;;
   "kern/Makefile.include" ) CONFIG_FILES="$CONFIG_FILES kern/Makefile.include" ;;
   "bin/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/Makefile" ;;
-  *) { { echo "$as_me:1541: error: invalid argument: $ac_config_target" >&5
+  "bin/test/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/test/Makefile" ;;
+  *) { { echo "$as_me:1590: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1634,8 +1683,14 @@ s,@RANLIB@,$RANLIB,;t t
 s,@ac_ct_RANLIB@,$ac_ct_RANLIB,;t t
 s,@MCPBINHEADERDIR@,$MCPBINHEADERDIR,;t t
 s,@MYRI_HOME@,$MYRI_HOME,;t t
+s,@lanaigccpath@,$lanaigccpath,;t t
 s,@KERNELLIST@,$KERNELLIST,;t t
 s,@PSM_OSDIR@,$PSM_OSDIR,;t t
+s,@CFLAG_WALL@,$CFLAG_WALL,;t t
+s,@CFLAG_G@,$CFLAG_G,;t t
+s,@CFLAG_COMPAT@,$CFLAG_COMPAT,;t t
+s,@CPPFLAG_MMD@,$CPPFLAG_MMD,;t t
+s,@DEPEXTENSION@,$DEPEXTENSION,;t t
 CEOF
 
 EOF
@@ -1745,7 +1800,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1748: creating $ac_file" >&5
+    { echo "$as_me:1803: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1763,7 +1818,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1766: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1821: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1776,7 +1831,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1779: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1834: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
