Doxyfile moved from dist to Documentation. New Makefile within Documentation.
git-svn-id: http://svn.ipd.uka.de/repos/ParaStation/trunk/mgmt@1641 34291a86-62e8-0310-8159-f060f8a2ee4e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1308,9 +1308,11 @@ ac_config_files="$ac_config_files bin/mon/Makefile"
 
 ac_config_files="$ac_config_files bin/java/psview/Makefile"
 
-ac_config_files="$ac_config_files dist/Makefile"
+ac_config_files="$ac_config_files Documentation/Makefile"
 
-ac_config_files="$ac_config_files dist/Doxyfile"
+ac_config_files="$ac_config_files Documentation/Doxyfile"
+
+ac_config_files="$ac_config_files dist/Makefile"
 
 ac_config_files="$ac_config_files dist_fe/Makefile"
 
@@ -1425,7 +1427,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1428: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1430: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1592,7 +1594,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1595: error: ambiguous option: $1
+    { { echo "$as_me:1597: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1611,7 +1613,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1614: error: unrecognized option: $1
+  -*) { { echo "$as_me:1616: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1669,11 +1671,12 @@ do
   "bin/mapper/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/mapper/Makefile" ;;
   "bin/mon/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/mon/Makefile" ;;
   "bin/java/psview/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/java/psview/Makefile" ;;
+  "Documentation/Makefile" ) CONFIG_FILES="$CONFIG_FILES Documentation/Makefile" ;;
+  "Documentation/Doxyfile" ) CONFIG_FILES="$CONFIG_FILES Documentation/Doxyfile" ;;
   "dist/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist/Makefile" ;;
-  "dist/Doxyfile" ) CONFIG_FILES="$CONFIG_FILES dist/Doxyfile" ;;
   "dist_fe/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist_fe/Makefile" ;;
   "dist_gui/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist_gui/Makefile" ;;
-  *) { { echo "$as_me:1676: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1679: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1891,7 +1894,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1894: creating $ac_file" >&5
+    { echo "$as_me:1897: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1909,7 +1912,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1912: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1915: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1922,7 +1925,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1925: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1928: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
