Move psmon and psview to dist_gui - the new parastation gui package. To build the java part enable jave with configure --enable-java.
git-svn-id: http://svn.ipd.uka.de/repos/ParaStation/trunk/mgmt@1626 34291a86-62e8-0310-8159-f060f8a2ee4e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -617,7 +617,6 @@ Optional Features:
   --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
   --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
   --enable-java    (default: disabled)
-  --enable-psmon    (default: disabled)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -809,7 +808,7 @@ if test -z "$CONFIG_SITE"; then
 fi
 for ac_site_file in $CONFIG_SITE; do
   if test -r "$ac_site_file"; then
-    { echo "$as_me:812: loading site script $ac_site_file" >&5
+    { echo "$as_me:811: loading site script $ac_site_file" >&5
 echo "$as_me: loading site script $ac_site_file" >&6;}
     cat "$ac_site_file" >&5
     . "$ac_site_file"
@@ -820,7 +819,7 @@ if test -r "$cache_file"; then
   # Some versions of bash will fail to source /dev/null (special
   # files actually), so we avoid doing that.
   if test -f "$cache_file"; then
-    { echo "$as_me:823: loading cache $cache_file" >&5
+    { echo "$as_me:822: loading cache $cache_file" >&5
 echo "$as_me: loading cache $cache_file" >&6;}
     case $cache_file in
       [\\/]* | ?:[\\/]* ) . $cache_file;;
@@ -828,7 +827,7 @@ echo "$as_me: loading cache $cache_file" >&6;}
     esac
   fi
 else
-  { echo "$as_me:831: creating cache $cache_file" >&5
+  { echo "$as_me:830: creating cache $cache_file" >&5
 echo "$as_me: creating cache $cache_file" >&6;}
   >$cache_file
 fi
@@ -844,21 +843,21 @@ for ac_var in `(set) 2>&1 |
   eval ac_new_val="\$ac_env_${ac_var}_value"
   case $ac_old_set,$ac_new_set in
     set,)
-      { echo "$as_me:847: error: \`$ac_var' was set to \`$ac_old_val' in the previous run" >&5
+      { echo "$as_me:846: error: \`$ac_var' was set to \`$ac_old_val' in the previous run" >&5
 echo "$as_me: error: \`$ac_var' was set to \`$ac_old_val' in the previous run" >&2;}
       ac_cache_corrupted=: ;;
     ,set)
-      { echo "$as_me:851: error: \`$ac_var' was not set in the previous run" >&5
+      { echo "$as_me:850: error: \`$ac_var' was not set in the previous run" >&5
 echo "$as_me: error: \`$ac_var' was not set in the previous run" >&2;}
       ac_cache_corrupted=: ;;
     ,);;
     *)
       if test "x$ac_old_val" != "x$ac_new_val"; then
-        { echo "$as_me:857: error: \`$ac_var' has changed since the previous run:" >&5
+        { echo "$as_me:856: error: \`$ac_var' has changed since the previous run:" >&5
 echo "$as_me: error: \`$ac_var' has changed since the previous run:" >&2;}
-        { echo "$as_me:859:   former value:  $ac_old_val" >&5
+        { echo "$as_me:858:   former value:  $ac_old_val" >&5
 echo "$as_me:   former value:  $ac_old_val" >&2;}
-        { echo "$as_me:861:   current value: $ac_new_val" >&5
+        { echo "$as_me:860:   current value: $ac_new_val" >&5
 echo "$as_me:   current value: $ac_new_val" >&2;}
         ac_cache_corrupted=:
       fi;;
@@ -877,9 +876,9 @@ echo "$as_me:   current value: $ac_new_val" >&2;}
   fi
 done
 if $ac_cache_corrupted; then
-  { echo "$as_me:880: error: changes in the environment can compromise the build" >&5
+  { echo "$as_me:879: error: changes in the environment can compromise the build" >&5
 echo "$as_me: error: changes in the environment can compromise the build" >&2;}
-  { { echo "$as_me:882: error: run \`make distclean' and/or \`rm $cache_file' and start over" >&5
+  { { echo "$as_me:881: error: run \`make distclean' and/or \`rm $cache_file' and start over" >&5
 echo "$as_me: error: run \`make distclean' and/or \`rm $cache_file' and start over" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -899,10 +898,10 @@ esac
 echo "#! $SHELL" >conftest.sh
 echo  "exit 0"   >>conftest.sh
 chmod +x conftest.sh
-if { (echo "$as_me:902: PATH=\".;.\"; conftest.sh") >&5
+if { (echo "$as_me:901: PATH=\".;.\"; conftest.sh") >&5
   (PATH=".;."; conftest.sh) 2>&5
   ac_status=$?
-  echo "$as_me:905: \$? = $ac_status" >&5
+  echo "$as_me:904: \$? = $ac_status" >&5
   (exit $ac_status); }; then
   ac_path_separator=';'
 else
@@ -928,7 +927,7 @@ for ac_dir in "scripts" $srcdir/"scripts"; do
   fi
 done
 if test -z "$ac_aux_dir"; then
-  { { echo "$as_me:931: error: cannot find install-sh or install.sh in \"scripts\" $srcdir/\"scripts\"" >&5
+  { { echo "$as_me:930: error: cannot find install-sh or install.sh in \"scripts\" $srcdir/\"scripts\"" >&5
 echo "$as_me: error: cannot find install-sh or install.sh in \"scripts\" $srcdir/\"scripts\"" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -938,11 +937,11 @@ ac_configure="$SHELL $ac_aux_dir/configure" # This should be Cygnus configure.
 
 # Make sure we can run config.sub.
 $ac_config_sub sun4 >/dev/null 2>&1 ||
-  { { echo "$as_me:941: error: cannot run $ac_config_sub" >&5
+  { { echo "$as_me:940: error: cannot run $ac_config_sub" >&5
 echo "$as_me: error: cannot run $ac_config_sub" >&2;}
    { (exit 1); exit 1; }; }
 
-echo "$as_me:945: checking build system type" >&5
+echo "$as_me:944: checking build system type" >&5
 echo $ECHO_N "checking build system type... $ECHO_C" >&6
 if test "${ac_cv_build+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -951,16 +950,16 @@ else
 test -z "$ac_cv_build_alias" &&
   ac_cv_build_alias=`$ac_config_guess`
 test -z "$ac_cv_build_alias" &&
-  { { echo "$as_me:954: error: cannot guess build type; you must specify one" >&5
+  { { echo "$as_me:953: error: cannot guess build type; you must specify one" >&5
 echo "$as_me: error: cannot guess build type; you must specify one" >&2;}
    { (exit 1); exit 1; }; }
 ac_cv_build=`$ac_config_sub $ac_cv_build_alias` ||
-  { { echo "$as_me:958: error: $ac_config_sub $ac_cv_build_alias failed." >&5
+  { { echo "$as_me:957: error: $ac_config_sub $ac_cv_build_alias failed." >&5
 echo "$as_me: error: $ac_config_sub $ac_cv_build_alias failed." >&2;}
    { (exit 1); exit 1; }; }
 
 fi
-echo "$as_me:963: result: $ac_cv_build" >&5
+echo "$as_me:962: result: $ac_cv_build" >&5
 echo "${ECHO_T}$ac_cv_build" >&6
 build=$ac_cv_build
 build_cpu=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
@@ -970,7 +969,7 @@ build_os=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 test -z "$build_alias" &&
   build_alias=$ac_cv_build
 
-echo "$as_me:973: checking host system type" >&5
+echo "$as_me:972: checking host system type" >&5
 echo $ECHO_N "checking host system type... $ECHO_C" >&6
 if test "${ac_cv_host+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -979,12 +978,12 @@ else
 test -z "$ac_cv_host_alias" &&
   ac_cv_host_alias=$ac_cv_build_alias
 ac_cv_host=`$ac_config_sub $ac_cv_host_alias` ||
-  { { echo "$as_me:982: error: $ac_config_sub $ac_cv_host_alias failed" >&5
+  { { echo "$as_me:981: error: $ac_config_sub $ac_cv_host_alias failed" >&5
 echo "$as_me: error: $ac_config_sub $ac_cv_host_alias failed" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
-echo "$as_me:987: result: $ac_cv_host" >&5
+echo "$as_me:986: result: $ac_cv_host" >&5
 echo "${ECHO_T}$ac_cv_host" >&6
 host=$ac_cv_host
 host_cpu=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
@@ -994,7 +993,7 @@ host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 test -z "$host_alias" &&
   host_alias=$ac_cv_host
 
-echo "$as_me:997: checking target system type" >&5
+echo "$as_me:996: checking target system type" >&5
 echo $ECHO_N "checking target system type... $ECHO_C" >&6
 if test "${ac_cv_target+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1003,12 +1002,12 @@ else
 test "x$ac_cv_target_alias" = "x" &&
   ac_cv_target_alias=$ac_cv_host_alias
 ac_cv_target=`$ac_config_sub $ac_cv_target_alias` ||
-  { { echo "$as_me:1006: error: $ac_config_sub $ac_cv_target_alias failed" >&5
+  { { echo "$as_me:1005: error: $ac_config_sub $ac_cv_target_alias failed" >&5
 echo "$as_me: error: $ac_config_sub $ac_cv_target_alias failed" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
-echo "$as_me:1011: result: $ac_cv_target" >&5
+echo "$as_me:1010: result: $ac_cv_target" >&5
 echo "${ECHO_T}$ac_cv_target" >&6
 target=$ac_cv_target
 target_cpu=`echo $ac_cv_target | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
@@ -1027,7 +1026,7 @@ test -z "$target_alias" &&
 if test -n "$ac_tool_prefix"; then
   # Extract the first word of "${ac_tool_prefix}ranlib", so it can be a program name with args.
 set dummy ${ac_tool_prefix}ranlib; ac_word=$2
-echo "$as_me:1030: checking for $ac_word" >&5
+echo "$as_me:1029: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_RANLIB+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1042,7 +1041,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_RANLIB="${ac_tool_prefix}ranlib"
-echo "$as_me:1045: found $ac_dir/$ac_word" >&5
+echo "$as_me:1044: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1050,10 +1049,10 @@ fi
 fi
 RANLIB=$ac_cv_prog_RANLIB
 if test -n "$RANLIB"; then
-  echo "$as_me:1053: result: $RANLIB" >&5
+  echo "$as_me:1052: result: $RANLIB" >&5
 echo "${ECHO_T}$RANLIB" >&6
 else
-  echo "$as_me:1056: result: no" >&5
+  echo "$as_me:1055: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1062,7 +1061,7 @@ if test -z "$ac_cv_prog_RANLIB"; then
   ac_ct_RANLIB=$RANLIB
   # Extract the first word of "ranlib", so it can be a program name with args.
 set dummy ranlib; ac_word=$2
-echo "$as_me:1065: checking for $ac_word" >&5
+echo "$as_me:1064: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_ac_ct_RANLIB+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1077,7 +1076,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_ac_ct_RANLIB="ranlib"
-echo "$as_me:1080: found $ac_dir/$ac_word" >&5
+echo "$as_me:1079: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1086,10 +1085,10 @@ fi
 fi
 ac_ct_RANLIB=$ac_cv_prog_ac_ct_RANLIB
 if test -n "$ac_ct_RANLIB"; then
-  echo "$as_me:1089: result: $ac_ct_RANLIB" >&5
+  echo "$as_me:1088: result: $ac_ct_RANLIB" >&5
 echo "${ECHO_T}$ac_ct_RANLIB" >&6
 else
-  echo "$as_me:1092: result: no" >&5
+  echo "$as_me:1091: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1131,7 +1130,7 @@ else
 
 		# Extract the first word of "lanai-gcc", so it can be a program name with args.
 set dummy lanai-gcc; ac_word=$2
-echo "$as_me:1134: checking for $ac_word" >&5
+echo "$as_me:1133: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_path_lanaigccpath+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1148,7 +1147,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   if $as_executable_p "$ac_dir/$ac_word"; then
    ac_cv_path_lanaigccpath="$ac_dir/$ac_word"
-   echo "$as_me:1151: found $ac_dir/$ac_word" >&5
+   echo "$as_me:1150: found $ac_dir/$ac_word" >&5
    break
 fi
 done
@@ -1159,10 +1158,10 @@ fi
 lanaigccpath=$ac_cv_path_lanaigccpath
 
 if test -n "$lanaigccpath"; then
-  echo "$as_me:1162: result: $lanaigccpath" >&5
+  echo "$as_me:1161: result: $lanaigccpath" >&5
 echo "${ECHO_T}$lanaigccpath" >&6
 else
-  echo "$as_me:1165: result: no" >&5
+  echo "$as_me:1164: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1200,19 +1199,6 @@ if test "${enable_java+set}" = set; then
 else
 
 	JAVA_ENABLED="no"
-
-fi;
-
-# default is no
-# Check whether --enable-psmon or --disable-psmon was given.
-if test "${enable_psmon+set}" = set; then
-  enableval="$enable_psmon"
-
-	PSMON_ENABLED=$enableval
-
-else
-
-	PSMON_ENABLED="no"
 
 fi;
 
@@ -1313,6 +1299,8 @@ ac_config_files="$ac_config_files dist/Makefile"
 ac_config_files="$ac_config_files dist/Doxyfile"
 
 ac_config_files="$ac_config_files dist_fe/Makefile"
+
+ac_config_files="$ac_config_files dist_gui/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -1423,7 +1411,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1426: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1414: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1590,7 +1578,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1593: error: ambiguous option: $1
+    { { echo "$as_me:1581: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1609,7 +1597,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1612: error: unrecognized option: $1
+  -*) { { echo "$as_me:1600: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1670,7 +1658,8 @@ do
   "dist/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist/Makefile" ;;
   "dist/Doxyfile" ) CONFIG_FILES="$CONFIG_FILES dist/Doxyfile" ;;
   "dist_fe/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist_fe/Makefile" ;;
-  *) { { echo "$as_me:1673: error: invalid argument: $ac_config_target" >&5
+  "dist_gui/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist_gui/Makefile" ;;
+  *) { { echo "$as_me:1662: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1769,7 +1758,6 @@ s,@MYRI_HOME@,$MYRI_HOME,;t t
 s,@lanaigccpath@,$lanaigccpath,;t t
 s,@KERNELLIST@,$KERNELLIST,;t t
 s,@JAVA_ENABLED@,$JAVA_ENABLED,;t t
-s,@PSMON_ENABLED@,$PSMON_ENABLED,;t t
 s,@PSM_OSDIR@,$PSM_OSDIR,;t t
 s,@CFLAG_WALL@,$CFLAG_WALL,;t t
 s,@CFLAG_G@,$CFLAG_G,;t t
@@ -1888,7 +1876,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1891: creating $ac_file" >&5
+    { echo "$as_me:1879: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1906,7 +1894,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1909: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1897: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1919,7 +1907,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1922: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1910: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
