New library pscommon.
git-svn-id: http://svn.ipd.uka.de/repos/ParaStation/trunk/mgmt@1108 34291a86-62e8-0310-8159-f060f8a2ee4e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1252,6 +1252,8 @@ ac_config_files="$ac_config_files lib/pse/Makefile"
 
 ac_config_files="$ac_config_files lib/psi/Makefile"
 
+ac_config_files="$ac_config_files lib/pscommon/Makefile"
+
 ac_config_files="$ac_config_files lib/putil/Makefile"
 
 ac_config_files="$ac_config_files kern/mcp/Makefile"
@@ -1375,7 +1377,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1378: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1380: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1542,7 +1544,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1545: error: ambiguous option: $1
+    { { echo "$as_me:1547: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1561,7 +1563,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1564: error: unrecognized option: $1
+  -*) { { echo "$as_me:1566: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1607,6 +1609,7 @@ do
   "lib/pvar/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pvar/Makefile" ;;
   "lib/pse/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pse/Makefile" ;;
   "lib/psi/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/psi/Makefile" ;;
+  "lib/pscommon/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pscommon/Makefile" ;;
   "lib/putil/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/putil/Makefile" ;;
   "kern/mcp/Makefile" ) CONFIG_FILES="$CONFIG_FILES kern/mcp/Makefile" ;;
   "kern/Makefile.include" ) CONFIG_FILES="$CONFIG_FILES kern/Makefile.include" ;;
@@ -1614,7 +1617,7 @@ do
   "bin/test/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/test/Makefile" ;;
   "bin/mapper/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/mapper/Makefile" ;;
   "dist/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist/Makefile" ;;
-  *) { { echo "$as_me:1617: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1620: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1830,7 +1833,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1833: creating $ac_file" >&5
+    { echo "$as_me:1836: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1848,7 +1851,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1851: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1854: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1861,7 +1864,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1864: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1867: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
