repaired top_srcdir
git-svn-id: http://svn.ipd.uka.de/repos/ParaStation/trunk/mgmt@953 34291a86-62e8-0310-8159-f060f8a2ee4e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1184,6 +1184,8 @@ else
 
 fi;
 
+TOP_SRCDIR=`cd \`dirname $0\`;pwd`
+
 case $target_os in
 linux)
 	PSM_OSDIR=kern/Linux
@@ -1199,6 +1201,7 @@ linux)
 	CPPFLAG_MMD=-MMD
 	DEPEXTENSION=.d
 	TRU64FILEADD=
+	LIBCURSES=ncurses
 	;;
 osf5.1)
 	PSM_OSDIR=kern/OSF1
@@ -1213,6 +1216,7 @@ osf5.1)
 	CPPFLAG_MMD=-MD
 	DEPEXTENSION=.o.d
 	TRU64FILEADD=_tru64
+	LIBCURSES=curses
 #	AC_CONFIG_FILES([kern/OSF1/Makefile])
 	;;
 *)
@@ -1232,8 +1236,6 @@ DOK
 
 fi
 
-top_srcdir=`path_cleanup $top_srcdir`
-
 ac_config_files="$ac_config_files Makefile"
 
 ac_config_files="$ac_config_files lib/pshal/Makefile"
@@ -1243,6 +1245,10 @@ ac_config_files="$ac_config_files lib/psport/Makefile"
 ac_config_files="$ac_config_files lib/arg/Makefile"
 
 ac_config_files="$ac_config_files lib/pvar/Makefile"
+
+ac_config_files="$ac_config_files lib/pse/Makefile"
+
+ac_config_files="$ac_config_files lib/psi/Makefile"
 
 ac_config_files="$ac_config_files kern/mcp/Makefile"
 
@@ -1363,7 +1369,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1366: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1372: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1530,7 +1536,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1533: error: ambiguous option: $1
+    { { echo "$as_me:1539: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1549,7 +1555,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1552: error: unrecognized option: $1
+  -*) { { echo "$as_me:1558: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1592,12 +1598,14 @@ do
   "lib/psport/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/psport/Makefile" ;;
   "lib/arg/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/arg/Makefile" ;;
   "lib/pvar/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pvar/Makefile" ;;
+  "lib/pse/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pse/Makefile" ;;
+  "lib/psi/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/psi/Makefile" ;;
   "kern/mcp/Makefile" ) CONFIG_FILES="$CONFIG_FILES kern/mcp/Makefile" ;;
   "kern/Makefile.include" ) CONFIG_FILES="$CONFIG_FILES kern/Makefile.include" ;;
   "bin/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/Makefile" ;;
   "bin/test/Makefile" ) CONFIG_FILES="$CONFIG_FILES bin/test/Makefile" ;;
   "dist/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist/Makefile" ;;
-  *) { { echo "$as_me:1600: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1608: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1702,6 +1710,8 @@ s,@CFLAG_COMPAT@,$CFLAG_COMPAT,;t t
 s,@CPPFLAG_MMD@,$CPPFLAG_MMD,;t t
 s,@DEPEXTENSION@,$DEPEXTENSION,;t t
 s,@TRU64FILEADD@,$TRU64FILEADD,;t t
+s,@LIBCURSES@,$LIBCURSES,;t t
+s,@TOP_SRCDIR@,$TOP_SRCDIR,;t t
 CEOF
 
 EOF
@@ -1811,7 +1821,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1814: creating $ac_file" >&5
+    { echo "$as_me:1824: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1829,7 +1839,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1832: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1842: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1842,7 +1852,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1845: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1855: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
