Add psmgmt package.(dist_mgmt)
git-svn-id: http://svn.ipd.uka.de/repos/ParaStation/trunk/mgmt@2029 34291a86-62e8-0310-8159-f060f8a2ee4e

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1282,6 +1282,8 @@ ac_config_files="$ac_config_files lib/psport/Makefile"
 
 ac_config_files="$ac_config_files lib/psport4/Makefile"
 
+ac_config_files="$ac_config_files lib/psport4shm/Makefile"
+
 ac_config_files="$ac_config_files lib/arg/Makefile"
 
 ac_config_files="$ac_config_files lib/pvar/Makefile"
@@ -1325,6 +1327,8 @@ ac_config_files="$ac_config_files dist_docu/Makefile"
 ac_config_files="$ac_config_files dist_gui/Makefile"
 
 ac_config_files="$ac_config_files dist_snmp/Makefile"
+
+ac_config_files="$ac_config_files dist_mgmt/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -1435,7 +1439,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1438: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1442: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1602,7 +1606,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1605: error: ambiguous option: $1
+    { { echo "$as_me:1609: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1621,7 +1625,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1624: error: unrecognized option: $1
+  -*) { { echo "$as_me:1628: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1666,6 +1670,7 @@ do
   "lib/pshal/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pshal/Makefile" ;;
   "lib/psport/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/psport/Makefile" ;;
   "lib/psport4/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/psport4/Makefile" ;;
+  "lib/psport4shm/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/psport4shm/Makefile" ;;
   "lib/arg/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/arg/Makefile" ;;
   "lib/pvar/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pvar/Makefile" ;;
   "lib/pse/Makefile" ) CONFIG_FILES="$CONFIG_FILES lib/pse/Makefile" ;;
@@ -1688,7 +1693,8 @@ do
   "dist_docu/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist_docu/Makefile" ;;
   "dist_gui/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist_gui/Makefile" ;;
   "dist_snmp/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist_snmp/Makefile" ;;
-  *) { { echo "$as_me:1691: error: invalid argument: $ac_config_target" >&5
+  "dist_mgmt/Makefile" ) CONFIG_FILES="$CONFIG_FILES dist_mgmt/Makefile" ;;
+  *) { { echo "$as_me:1697: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1906,7 +1912,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1909: creating $ac_file" >&5
+    { echo "$as_me:1915: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1924,7 +1930,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1927: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1933: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1937,7 +1943,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1940: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1946: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
