changed start procedure for tru64
git-svn-id: http://svn.ipd.uka.de/repos/ParaStation/trunk/mgmt@1001 34291a86-62e8-0310-8159-f060f8a2ee4e

diff --git a/scripts/parastation_tru64 b/scripts/parastation_tru64
--- a/scripts/parastation_tru64
+++ b/scripts/parastation_tru64
@@ -7,10 +7,15 @@ PSCONFIG=`dirname $0`/psconfig
 
 case "$1" in
     start)
-	sysconfig -s "$MODULENAME" | grep -q unloaded || $0 stop
-
-	sysconfig -c "$MODULENAME" || exit 1
-	
+	CONFIGURED=`sysconfig -s $MODULENAME | grep -w configured`
+        if [ "$CONFIGURED" = "" ] ; then
+	    sysconfig -c "$MODULENAME"
+            if [ $? -ne 0 ]
+            then
+                  echo "Failed to configure subsystem: " $MODULENAME
+		  exit 1
+            fi
+        fi
 	$PSCONFIG -key "$PS_LIC" || exit 2
 	$PSCONFIG -id "$PS_ID" "$PS_ROUTEFILE" || exit 3
 	
