Try to find out if GM's startup was successful. Enable gm_counters to psiadmin.
git-svn-id: http://svn.ipd.uka.de/repos/ParaStation/trunk/mgmt@2398 34291a86-62e8-0310-8159-f060f8a2ee4e

diff --git a/scripts/ps_gm b/scripts/ps_gm
--- a/scripts/ps_gm
+++ b/scripts/ps_gm
@@ -6,7 +6,7 @@
 #
 # Author: Jens Hauke <hauke@par-tec.com>, Norbert Eicker <eicker@par-tec.com>
 #
-# $Id: ps_gm,v 1.1 2003/06/20 14:24:52 eicker Exp $
+# $Id: ps_gm,v 1.2 2003/07/25 13:15:28 eicker Exp $
 #
 
 #checks
@@ -18,11 +18,17 @@ PS_IPENABLED=${PS_IPENABLED-"0"}
 PS_IPPREFIX=${PS_IPPREFIX-"192.168.48"}
 PS_IPPREFIXLEN=${PS_IPPREFIXLEN-"20"}
 
+PS_GMCOUNTERS=${PS_INSTALLDIR}/scripts/ps_gmcounters
+
 GM_INSTALLDIR=${GM_INSTALLDIR-"/opt/gm"}
-GMCOUNTER=${GM_INSTALLDIR}/
 case "$1" in
     start)
-	/etc/init.d/gm start
+	# /etc/init.d/gm start
+	out=`/etc/init.d/gm start | grep "Could not install GM module"`
+	if [ -n "$out" ]; then
+	    echo $out
+	    exit 1
+	fi
 
 	# if [ "$PS_IPENABLED" = "1" ]; then
 	#     /sbin/ifconfig myri0 up
@@ -38,13 +44,19 @@ case "$1" in
 	;;
 
     statusheader)
-	echo
-	# ${GMCOUNTER} | head -1
+	if [ -x ${PS_GMCOUNTERS} ]; then
+		${PS_GMCOUNTERS} -header
+	else
+		echo "  **** Cannot get header ****"
+	fi
 	;;
 
     status)
-	echo
-	#${GMCOUNTER} | tail -1
+	if [ -x ${PS_GMCOUNTERS} ]; then
+		${PS_GMCOUNTERS}
+	else
+		echo "  No counters available"
+	fi
 	;;
 
     *)
