New option -x. New -n feature for ranges like -n carla\[1-16\] or -n alice-\[001-010\]. New -sync option for file distribution. New autocd feature to change to pwd on remote with $HOME substitution.
git-svn-id: http://svn.ipd.uka.de/repos/ParaStation/trunk/mgmt@2410 34291a86-62e8-0310-8159-f060f8a2ee4e

diff --git a/scripts/psh b/scripts/psh
--- a/scripts/psh
+++ b/scripts/psh
@@ -20,6 +20,7 @@ D_CONFIG="${D_CONFIG_D}/default"
 D_RCMD="ssh -x"
 D_MAXRCMD=32
 D_DIFFCMD="diff -q"
+D_AUTOCD="cd ${PWD/${HOME}/~};"
 TMPTEMPLATE="/tmp/pshout.XXXXXX"
 
 ############################
@@ -44,6 +45,8 @@ function help
 {
 cat <<EOF
 Usage: psh [OPTION]... command
+       psh [OPTION]... -sync filename...
+       psh [OPTION]... -sync dirname...
 
 Options:
    -g|-group {group}      : Use group defined in $D_CONFIG_D 
@@ -51,60 +54,73 @@ Options:
    -c|-configfile {cfile} : Set configuration file 
                             (default "$D_CONFIG").
    -n|-node {nodename}    : Append one {nodename} to nodelist.
+   -x|-xnode {nodename}   : Exclude one {nodename} from nodelist.
+   -s|-sync               : copy one file to all nodes.
    -rcmd {rcmd}           : set remote shell (default "$D_RCMD").
    -max {nmax}            : dont start more than {nmax} remote shells
                             at the same time (default $D_MAXRCMD).
    -diff {cmd}            : Program which compares the outputs 
                             (default "$D_DIFFCMD")
+   -autocd                : remote dir (default "cd \${PWD/\${HOME}/~};")
+                            use -autocd "" to disable autocd.
    -v|-verbose            : Be verbose
    -h|-help               : help
 EOF
 }
 
-
 function parse()
 {
 #    echo Parse "$*"
     case "$1" in
-	-g|-group)
-	    CONFIG="${CONFIG_D}/$2"
+	-g|${prearg}group)
+            CONFIG="${CONFIG_D}/$2"
 	    nopts=2
 	    ;;
-	-c|-configfile) 
+	-c|${prearg}configfile) 
 	    CONFIG="$2"
 	    nopts=2
 	    ;;
-	-n|-node)
-	    NODES=(${NODES[*]} "$2")
+	-n|${prearg}node)
+	    NODES=(${NODES[*]} $(nameexpand "$2"))
 	    nopts=2
 	    ;;
-	-rcmd)
+	-s|-sync)
+	    SYNC=1
+	    nopts=1
+	    ;;
+	${prearg}rcmd)
 	    RCMD=${RCMD-"$2"}
 	    nopts=2
 	    ;;
-	-max)
+	${prearg}max)
 	    MAXRCMD=${MAXRCMD-"$2"}
 	    nopts=2
 	    ;;
-	-diff)
+	${prearg}diff)
 	    DIFFCMD=${DIFFCMD-"$2"}
 	    nopts=2
 	    ;;
-#	-x)
-#            nodes=$NODES;
-#	    NODES=""
-#	    nopts=2
-#	    ;;
-	-v|-verbose)
+	-x|${prearg}xnode)
+	    XNODES=(${XNODES[*]} $(nameexpand "$2"))
+	    nopts=2
+	    ;;
+	${prearg}autocd)
+	    AUTOCD=${AUTOCD-"$2"}
+	    nopts=2
+	    ;;
+	-v|${prearg}verbose)
 	    VERBOSE=1
 	    nopts=1
 	    ;;
-	-h|-help)
+	-h|${prearg}help)
 	    help
 	    exit 1
 	    ;;
-	-*)
-	    echo "$optsource : unknown option $1."
+	${prearg}#*) # comment
+	    nopts=1
+	    ;;
+	${prearg}*)
+	    echo "$optsource : unknown option \"$1\"."
 	    help
 	    exit 1;
 	    ;;
@@ -204,6 +220,61 @@ END{
 '
 }
 
+function nameexpand()
+{
+    echo $*| awk '
+BEGIN{ RS=" " }
+
+function expand(name,pat)
+{
+    el = split(pat, sp, ",");
+    for (i=1;i<=el;i++) {
+      eel = split(sp[i], ssp, "-");
+      if (eel<=1) { /* one or no value */
+          x=name;
+          sub("\\["pat"\\]",ssp[1],x);
+          print x;
+      } else { /* range */
+          if (substr(ssp[1],1,1) == "0") {
+              /* leading 0s */
+              for (j = ssp[1] + 0; j <= ssp[2] + 0; j++) {
+                  x=name;
+                  sub("\\["pat"\\]",sprintf("%0"length(ssp[1])"d", j),x);
+                  print x;
+              } 
+          } else {
+              for (j = ssp[1] + 0; j <= ssp[2] + 0; j++) {
+                  x=name;
+                  sub("\\["pat"\\]",sprintf("%"length(ssp[1])"d", j),x);
+                  print x;
+              } 
+           }
+      }
+    }
+}
+
+{
+   hostname=$1;
+   match(hostname, "\\[(.*)\\]", s);
+   if (s[0] != "") {
+       expand(hostname, s[1]);
+   } else {
+       print hostname;
+   }
+}
+'
+}
+
+#
+# remove $1 from nodelist
+#
+function del_node()
+{
+    NODES=" ${NODES[*]} "
+    NODES=(${NODES/" $1 "/" "})
+}
+
+
 #
 # Just fetch SIGINT
 #
@@ -239,6 +310,7 @@ CONFIG_D="$D_CONFIG_D"
 # Parse commandline
 #
 optsource="Commandline"
+prearg="-"
 nopts=1
 while [ $nopts != 0 ] ; do
     parse "$@"
@@ -248,19 +320,26 @@ done
 #
 # Read configuration
 #
+prearg=""
 if [ -f "${CONFIG}" ]; then
-    line=1
+    line=0
     while read command opts; do
 	line=$(( $line + 1 ))
 	optsource="$CONFIG:$line"
-	parse $command "$opts"
+	if [ ! -z "$command" ]; then
+	    parse "$command" "$opts"
+	fi
     done < "${CONFIG}"
 fi
 
 COMMAND="$*"
 
 if [ x"$COMMAND" = x ];then
-    echo "Error: Missing command"
+    if [ x"$SYNC" = x ]; then
+	echo "Error: Missing command"
+    else
+	echo "Error: Missing filename"
+    fi
     help
     exit 1
 fi
@@ -271,10 +350,36 @@ if [ "${#NODES[*]}" = 0 ];then
     exit 1
 fi
 
+for((i = 0 ;i < ${#XNODES[*]} ;i++)); do
+    del_node ${XNODES[$i]}
+done
+
 
 RCMD="${RCMD-$D_RCMD}"
 MAXRCMD="${MAXRCMD-$D_MAXRCMD}"
 DIFFCMD="${DIFFCMD-$D_DIFFCMD}"
+AUTOCD="${AUTOCD-$D_AUTOCD}"
+
+if [ "${SYNC}" = 1 ]; then
+    FILELIST="$COMMAND"
+    COMMAND="tar xvf -";
+    TARFILE=$(mktemp $TMPTEMPLATE)
+    TMPFILES="$TMPFILES $TARFILE"
+    echo "Prepare files for distribution:"
+    tar cvf "${TARFILE}" ${FILELIST}
+    echo "Continue(y/n)?[n]"
+    read c
+    case "$c" in
+	y|Y)
+	;;
+	*)
+	    exit 1;
+    esac
+    INPUT="${TARFILE}"
+else
+    INPUT="/dev/null"
+fi
+
 
 
 if [ "$VERBOSE" = 1 ];then
@@ -295,9 +400,9 @@ trap killcurrent SIGINT
 for ((i = 0; i < ${#NODES[*]} ; i++)); do
     host=${NODES[$i]}
     OUTFILE=$(mktemp $TMPTEMPLATE)
-    OUTPUTS=(${OUTPUTS[*]} ${OUTFILE})
     TMPFILES="$TMPFILES $OUTFILE"
-    $RCMD "$host" "$COMMAND" > $OUTFILE 2>&1 &
+    OUTPUTS=(${OUTPUTS[*]} ${OUTFILE})
+    < "${INPUT}" $RCMD "$host" "$AUTOCD$COMMAND" > $OUTFILE 2>&1 &
     PIDS=(${PIDS[*]} $!)
     if [ "$VERBOSE" = 1 ];then
 	echo "$RCMD $host $COMMAND"
